name: Release
on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Git user and use GPG for commit signing
        run: |
          git config --global user.email "kostysh@gmail.com"
          git config --global user.name "@$GITHUB_ACTOR"
          git config --global commit.gpgsign true
          git config --global gpg.program gpg2
          git config --global user.signingKey $(gpg --list-secret-keys --keyid-format LONG --with-colons | grep sec | head -n 1 | cut -d ':' -f 5)
      - name: Version Packages
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            pnpm lerna version --allow-branch master
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            pnpm lerna version --conventional-prerelease --preid beta --allow-branch beta
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: pnpm lerna publish from-package --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
